#!/bin/bash

echo "--Starting personalize"
sudo apt install zsh
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
git clone https://github.com/pyenv/pyenv.git ~/.pyenv